import java.io.File;
import java.io.IOException;
import java.util.Scanner;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class FileCreator {

    public String FileCreator (String name)  {
        File file = new File(name);
        if(!checkFileExist(file)){
            try {
                file.createNewFile();
            } catch (IOException e) {
                e.printStackTrace();
            }
            return "File is created!";
        }
        else
            return "File already exists.";
    }

    public boolean checkFileExist(File file) {
        if (file.exists())
            return true;
        else return false;
    }

    public void main(String[] args) {
        System.out.println(FileCreator(InputHandler()));
    }

    public String InputHandler() {
        Scanner sc = new Scanner(System.in);
        return sc.nextLine();
    }


}
