/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;

import java.io.File;

import static org.testng.Assert.*;

public class FileCreatorTest {
    String fileName = "1234Test.txt";

    @AfterMethod
    public void deleteCreatedFile(){
        File file = new File(fileName);
        if(file.exists())
            file.delete();
    }

    @Test public void checkNewFileCreatedExists() {
        FileCreator classUnderTest = new FileCreator();
        classUnderTest.FileCreator(fileName);
        assertTrue(classUnderTest.checkFileExist(new File(fileName)));
    }
    
    @Test public void checkNewFileCreated() {
        FileCreator classUnderTest = new FileCreator();
        assertEquals(classUnderTest.FileCreator(fileName),"File is created!");
    }
    
    @Test public void checkFileExist() {
        FileCreator classUnderTest = new FileCreator();
        classUnderTest.FileCreator(fileName);
        assertEquals(classUnderTest.FileCreator(fileName),"File already exists.");
    }


}
